
services:
    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - 27017:27017

    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
        ME_CONFIG_BASICAUTH: false

    api_gateway:
      build: ./api-gateway-service
      restart: always
      ports:
        - 3000:3000
      environment:
        LINK_MICROSERVICE_URL: ${LINK_MICROSERVICE_URL}
        SHORTEN_MICROSERVICE_URL: ${SHORTEN_MICROSERVICE_URL}
        API_GATEWAY_HOST: ${API_GATEWAY_HOST}
        PORT: ${PORT}

    link_microservice:
      build: ./managment-service
      restart: always
      ports:
        - 5000:5000
      depends_on:
        - mongo
      environment:
        MONGODB_URI: ${MONGODB_URI}
        MONGODB_DATABASE: ${MONGODB_DATABASE}
        LINK_MICROSERVICE_URL: ${LINK_MICROSERVICE_URL}
        SHORTEN_MICROSERVICE_URL: ${SHORTEN_MICROSERVICE_URL}

    shorten_microservice:
      build: ./redirect-service
      restart: always
      ports:
        - 5001:5001
      environment:
        LINK_MICROSERVICE_URL: ${LINK_MICROSERVICE_URL}
        SHORTEN_MICROSERVICE_URL: ${SHORTEN_MICROSERVICE_URL}